language:
  - cpp

os:
  - linux

# Container-based infrastructure (Linux)
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-can-I-use-container-based-infrastructure%3F
sudo:
  - false

dist:
  - trusty

# Install packages differs for container-based infrastructure
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-do-I-install-APT-sources-and-packages%3F
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - gcc-5

install:
  # Info about OS
  - uname -a

script:
  - which g++-5
  - which gcc-5
  - g++-5 --version
  - gcc-5 --version

branches:
  except:
    - /^pr\..*/
